### ISSUE TITLE
link quebrado

### ISSUE THREAD

**Issue by geraugu** [eliezerfb/elections-prediction-capstone-ndml#1]
Olá amigo tudo bem?
vc tem esse arquivo disponível?
Bens: http://agencia.tse.jus.br/estatistica/sead/odsele/bem_candidato/bem_candidato_2014.zip

não está mais disponível no site do tse.

**Comment by eliezerfb** [comment]
Aparentemente o link agora está OK. 
Vi essa issue só agora...
